language: ruby
rvm:
  - 2.1.1
before_script:
  - git config --global user.email "sh19910711+ynkkowrv0b14@gmail.com"
  - git config --global user.name "Mr. Bot"
script:
  - ./script/travis/bootstrap
env:
  - secure: "WjvNyV5zbz0YwPYA5/LyvzbAdKk4JSUlk5s1nAFTcOaAXYnfN0gGusH66KtE3GiL6J5vLe12gj73frovvd6YZRgzj91q3EIp55Y+VEkFIoP4TAFwtSSxCjnr+h9fTbkyQA8uL0ThvOvJ+0newzIzaPiaM5oT8bPUqR0wZNgkuqw="
