#!/bin/bash

bekobrew_dir=tmp/bekobrew-gh-pages
git clone --single-branch -b gh-pages git://github.com/u-aizu/bekobrew.git ${bekobrew_dir}
cp tmp/installer/install.bash ${bekobrew_dir}
pushd ${bekobrew_dir}
git add install.bash
git commit --allow-empty -m "update installer"
git push --quiet https://${GITHUB_TOKEN}@github.com/u-aizu/bekobrew.git gh-pages
popd
