#!/bin/bash

function build() {
  # load config
  source BuildConfig

  local prefix=tmp/installer

  # build
  rm -rf ${prefix} || true
  mkdir -p ${prefix} || true

  cp src/installer/install.bash ${prefix}/install.bash
  chmod -w ${prefix}/install.bash
}

build
