#!/bin/bash

function build() {
  # load config
  source BuildConfig

  local prefix=tmp/bekobrew

  # build bekobrew command
  rm -rf ${prefix} || true
  mkdir -p ${prefix} || true

  sed '1i #!/bin/bash' ./src/bekobrew/bekobrew.bash > ${prefix}/bekobrew
  cp -r ./src/bekobrew/sub_command ${prefix}/sub_command

  chmod a+x ${prefix}/bekobrew
  chmod a-w ${prefix}/bekobrew
}

build
